--게시판 테이블 생성
CREATE TABLE BOARD(
    IDX     NUMBER PRIMARY KEY,  --글번호
    TITLE   VARCHAR2(100) NOT NULL, -- 제목
    CONTENT VARCHAR2(1000) NOT NULL,-- 내용
    WRITER  VARCHAR2(50) NOT NULL, -- 작성자
    REGDATE DATE DEFAULT SYSDATE --등록딜
);

--시퀀스 생성
CREATE SEQUENCE SEQ_BOARD; -- IDX컬럼 데이터목적


CREATE TABLE BOARD2
( BNO    NUMBER  PRIMARY KEY,
 TITLE VARCHAR2(100) NOT NULL
 );
 
 CREATE TABLE BOARD3 (
 BNO    NUMBER  CONSTRAINT PK_BOARD3 PRIMARY KEY,
 TITLE VARCHAR2(100) NOT NULL
 );
 
 